name: Docker Build y Push

on:
push:
branches: [ main ]
pull_request:

jobs:
build:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Login Docker Hub
    run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u wearygamelov1 --password-stdin

  - name: Install dependencies
    run: npm install

  - name: Run unit tests
    run: npm test

  - name: Generate coverage metrics
    run: npm run test:coverage

  - name: Build Docker image
    run: docker build -t wearygamelov1/mi-app:latest .

  - name: Push Docker image
    run: docker push wearygamelov1/mi-app:latest
```

